spring.application.name=food-delivery
server.port=8051

# ACTUATOR
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always

# CIRCUIT BREAKER
resilience4j.circuitbreaker.instances.externalService.sliding-window-size=10
resilience4j.circuitbreaker.instances.externalService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.externalService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.externalService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.externalService.permitted-number-of-calls-in-half-open-state=3

# BULKHEAD
resilience4j.bulkhead.instances.orderService.max-concurrent-calls=3
resilience4j.bulkhead.instances.orderService.max-wait-duration=1s

# LOGGING
logging.level.io.github.resilience4j=DEBUG
logging.level.com.fooddelivery=DEBUG